
/*★ 제약 조건에서 가장 중요한 건 primary key 와 foreign key 의 특성과 관계 ★ */

/*14-4 PRIMARY KEY*/
/* 실습 14-29 */
create table table_pk(
    LOGIN_ID VARCHAR2(20) PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20)
);

DESC TABLE_PK;


/* 실습 14-30 */
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME LIKE 'TABLE_PK%';
    
    
/* 실습 14-31 */
SELECT INDEX_NAME, TABLE_OWNER, TABLE_NAME
        FROM USER_INDEXES
    WHERE TABLE_NAME LIKE 'TABLE_PK%';  /* 특정 열을 primary key 로 지정하면 해당 열에는 자동으로 인덱스가 만들어진다.*/
    

/* 실습 14-32 제약 조건 이름 직접 지정하기 */
CREATE TABLE TABLE_PK2(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLPK2_LGNID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLPK2_LGNPW_NN NOT NULL,
    TEL VARCHAR2(20)
);


/* 실습 14-33 */
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('TEST_ID_01', 'PWD01', '010-1234-5678');

SELECT * FROM table_pk;


/* 실습 14-34 */
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('TEST_ID_01', 'PWD01', '010-1234-5678'); /* UNIQUE 제약 조건에 걸림 */

SELECT * FROM TABLE_PK;



/* 14-5 FOREIGN KEY */
/* 실습 14-37 */
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, R_OWNER, R_CONSTRAINT_NAME
        FROM USER_CONSTRAINTS
    WHERE TABLE_NAME IN ('EMP', 'DEPT');
    

/* 실습 14-38 */
INSERT INTO EMP
    VALUES (9999, '홍길동', 'CLERK', '7788', TO_DATE('2017/04/30', 'YYYY/MM/DD'), 1200, NULL, 50);
    
    
/* 실습 14-39 */
CREATE TABLE DEPT_FK(
    DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);

DESC DEPT_FK;


/* 실습 14-40 */
CREATE TABLE EMP_FK(
    EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7, 2),
    COMM NUMBER(7, 2),
    DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK (DEPTNO)
);

DESC EMP_FK;

INSERT INTO DEPT_FK
    VALUES (10, '총무부', '서울');
    
    
/* 14-6 CHECK 제약 조건 */
CREATE TABLE TABLE_CHECK(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLCH_LOGINPW_CK CHECK (LENGTH(LOGIN_PWD) > 3),
    TEL VARCHAR2(20)
);


/* 실습 14-46 */
INSERT INTO TABLE_CHECK
    VALUES('TEST_ID_01', 'PW1', '010-2659-6854'); /* LENGTH(LOGIN_PWD) > 3 조건을 만족하지 않기 때문에 오류 */
    
    
 /* 14-7 DEFAULT */
 /* 실습 14-49 */
CREATE TABLE TABLE_DEFAULT(
    LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK2_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) DEFAULT '1234',
    TEL VARCHAR2(20)
);


/* 실습 14-50 */
INSERT INTO TABLE_DEFAULT VALUES ('TEST_ID', NULL, '010-1234-5678');
INSERT INTO TABLE_DEFAULT (LOGIN_ID, TEL) VALUES ('TEST_ID2', '010-2345-6789');

SELECT * FROM TABLE_DEFAULT;

 
 









